/**
 * Real team names from past HackNU hackathons at Nazarbayev University — the
 * few-shot examples for the AI team-name generator (see ai.server.ts).
 */
export const TEAM_NAME_EXAMPLES: string[] = [
  '3A',
  '4REAL',
  '4ward',
  '4eps',
  '9labs',
  'Academic Weapon',
  'ADA',
  'Adilas',
  'AI TIger',
  'AiMe',
  'Aitushniki',
  'AKA-47',
  'Akatsuki',
  'Alikhan',
  'Amylase',
  'Apex',
  'Aquarium',
  'AR power',
  'ARA',
  'Aurora',
  'B.A.D. Logic',
  'B.Y.N.K.',
  'Babonizm',
  'Besties',
  'BFFS',
  'Black panther',
  'BOND',
  'Boundary Breakers',
  'BrainHack',
  'Bubble sort',
  'Byte sized brains',
  'ByteTeam',
  'Carpe_Diem!',
  'Chill Team',
  'Code and creativity',
  'Code QuAD',
  'Code++',
  'code_break',
  'CodeX',
  'Codix',
  'Coffee to Code',
  'Ctrl+Win',
  'ctrl freaks',
  'CTRL+C+V',
  'Cyber bloom',
  'D&A squared',
  'DaaS',
  'Dark Spark',
  'Desperate Engineers',
  'Diligence',
  'DNA and NDA',
  'Doomers',
  'Dreamers',
  'Dropouts',
  'Dynamic duo',
  'EchoTeam',
  'EdgeMap',
  'Electrified',
  'Elite Basbards',
  'Embers',
  'Enchantix',
  'Enigma',
  'Error404',
  'EVE',
  'Falcons',
  'Fire Hawks',
  'Fortune',
  'Front2Back',
  'Frosted Dahlia',
  'GenieLab',
  'Gilmore',
  'Gradient',
  'Hackrise',
  'Heart Drive ll',
  'Herizon',
  'hixie',
  'Hollow_Leaf',
  'HunterX',
  'Infinite Loop',
  'ItTakesOne',
  'Just a team',
  'Kernel Group',
  'Lalaland',
  'Lambda',
  'Last One',
  'LeviOsa',
  'Light',
  'LLaMAr',
  'Luck',
  'Luna',
  'MABS',
  'Mavericks',
  'MindHack',
  'Ninjas',
  'NomadCoders',
  'Nomadium',
  'Nu Poehali',
  'Nyan kitties',
  'Optimizers',
  'Overfitters',
  'pain au chocolat',
  'PeakMinds',
  'Peacedata',
  'Pi Chasers',
  'Prompt Injectors',
  'Push & Pray',
  'Quatro',
  'return 0',
  'Rockets',
  'S@mur.AI',
  'Scrambled Eggs',
  'Seals',
  'Sharks',
  'Shiniies',
  'Singularity',
  'Sky is the limit',
  'Smoooth Operator',
  'SoloX',
  'STEM Stars',
  'SynapseX',
  'Team Core',
  'The Darkness',
  'Thinktank X',
  'TrioVibe',
  'TroubleShooters',
  'Twins',
  'TypeWriters',
  'UndefinedWarrioirs',
  'Wake-Sleep',
  'yoloyo',
  'Yurt',
  'Claude Did This',
  'GPT Heroes',
  'Copilot Crew',
  'Vibecoders',
  'AI Slop Enjoyers',
  'Hallucination Squad',
  'Token Limit',
  'Prompt Engineers',
  '10x Developers',
  'Gemini Gang',
  'Ollama Crew',
  'Context Window',
  'RAG Raiders',
  'Stack Overflow Survivors',
  'Merge Conflict',
  '404 Brain Not Found',
  'Rubber Duck Debuggers',
  'Spaghetti Code',
  'YOLO Deploy',
  'Tab vs Space',
  'Semicolon Warriors',
  'Off By One',
  'It Works On My Machine',
  'WIP',
  'TODO Squad',
  'Technical Debt',
  'Ship It',
  '2am Coders',
  'Caffeine Overdose',
  'Code Monkey',
  'Bug Zappers',
  'Cache Invalidation',
  'Race Condition',
  'Regex Wizards',
  'Legacy Code Warriors',
  'Refactor This',
  'Feature Creep',
  'Pair Programming',
  'Hotfix Heroes',
  'MVP Squad',
  'Pivot Masters',
  'Agile AF',
  'Sprint Warriors',
  'Retro Gang',
  'Dev Ducks',
  'Commit Message',
  'Production Ready',
];

/**
 * Returns n randomly sampled names from the examples array.
 * Called at request time so each generation sees a different subset.
 */
export function sampleExamples(n = 20): string[] {
  const shuffled = [...TEAM_NAME_EXAMPLES].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}
